### ISSUE TITLE
Pre-trained model files

### ISSUE THREAD

**Issue by GalPatel** [swabhs/scaffolding#2]
Hello,

Although I followed the instruction in the README, I was not able to run "Step 3: Test" on the provided pre-trained models. The error is because no model.tar.gz file is found. How should I run predictions on these models with the provided weights and config files?

**Comment by swabhs** [comment]
You have to download the files from the provided links in order to run test - are these links (https://github.com/swabhs/scaffolding#step-2-get-pre-trained-models) working for you?

**Comment by GalPatel** [comment]
I did follow the README's instructions and downloaded everything. Yet, when running the command in step 3, model files are missing.
